version: "3.8"  # 指定 Docker Compose 文件格式版本

services:
  redis-asr:
    image: redis:8.0.1
    container_name: redis-kb
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD:-changeme}
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data  # 将容器中的MySQL数据存储目录挂载到宿主机目录（持久化数据）
    networks:
      - ai-platform-network

networks:
  ai-platform-network:
    external: true